# Generated by Django 4.2.4 on 2023-08-31 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alignment",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("element", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "alignment",
            },
        ),
        migrations.CreateModel(
            name="Alignment2Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.alignment",
                    ),
                ),
            ],
            options={
                "db_table": "alignment2variant",
            },
        ),
        migrations.CreateModel(
            name="AnnotationType",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "seq_ontology",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("region", models.CharField(blank=True, max_length=50, null=True)),
                ("test", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "db_table": "annotation_type",
            },
        ),
        migrations.CreateModel(
            name="Element",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("type", models.TextField(blank=True, null=True)),
                ("accession", models.TextField(blank=True, null=True, unique=True)),
                ("symbol", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("strand", models.BigIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True, null=True)),
                ("standard", models.BigIntegerField(blank=True, null=True)),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "element",
            },
        ),
        migrations.CreateModel(
            name="Lineages",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("lineage", models.CharField(max_length=100)),
                ("sublineage", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "lineages",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("datatype", models.TextField(blank=True, null=True)),
                ("querytype", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("target", models.TextField(blank=True, null=True)),
                ("standard", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "property",
            },
        ),
        migrations.CreateModel(
            name="Sequence",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("seqhash", models.CharField(max_length=200, unique=True)),
            ],
            options={
                "db_table": "sequence",
            },
        ),
        migrations.CreateModel(
            name="TranslationGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "translation_group",
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("ref", models.TextField(blank=True, null=True)),
                ("alt", models.TextField(blank=True, null=True)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
                ("label", models.TextField(blank=True, null=True)),
                ("frameshift", models.BigIntegerField(blank=True, null=True)),
                ("sample_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nuc_profile",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "aa_profile",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("imported", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "collection_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("isolate", models.CharField(blank=True, max_length=50, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("seq_tech", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("host", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "genome_completeness",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_accession",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "alignments",
                    models.ManyToManyField(
                        through="rest_api.Alignment2Variant", to="rest_api.alignment"
                    ),
                ),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.element",
                    ),
                ),
            ],
            options={
                "db_table": "variant",
            },
        ),
        migrations.CreateModel(
            name="Sample",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.TextField(blank=True, null=True, unique=True)),
                ("datahash", models.TextField(blank=True, null=True)),
                (
                    "sequence",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="samples",
                        to="rest_api.sequence",
                    ),
                ),
            ],
            options={
                "db_table": "sample",
            },
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("accession", models.TextField(blank=True, null=True, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("organism", models.TextField(blank=True, null=True)),
                ("standard", models.BigIntegerField(blank=True, null=True)),
                (
                    "translation_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.translationgroup",
                    ),
                ),
            ],
            options={
                "db_table": "reference",
            },
        ),
        migrations.CreateModel(
            name="Molecule",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("type", models.TextField(blank=True, null=True)),
                ("accession", models.TextField(blank=True, null=True, unique=True)),
                ("symbol", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("length", models.BigIntegerField(blank=True, null=True)),
                ("segment", models.BigIntegerField(blank=True, null=True)),
                ("standard", models.BigIntegerField(blank=True, null=True)),
                (
                    "reference",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.reference",
                    ),
                ),
            ],
            options={
                "db_table": "molecule",
            },
        ),
        migrations.CreateModel(
            name="Elempart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start", models.BigIntegerField()),
                ("end", models.BigIntegerField()),
                ("strand", models.BigIntegerField()),
                ("base", models.FloatField()),
                ("segment", models.BigIntegerField()),
                (
                    "element",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.element",
                    ),
                ),
            ],
            options={
                "db_table": "elempart",
            },
        ),
        migrations.AddField(
            model_name="element",
            name="molecule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.molecule",
            ),
        ),
        migrations.AddField(
            model_name="alignment2variant",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rest_api.variant"
            ),
        ),
        migrations.AddField(
            model_name="alignment",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.sequence",
            ),
        ),
        migrations.CreateModel(
            name="Variant2Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_integer", models.BigIntegerField(blank=True, null=True)),
                (
                    "value_float",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_varchar", models.TextField(blank=True, null=True)),
                ("value_blob", models.BinaryField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_zip", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.property",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.variant",
                    ),
                ),
            ],
            options={
                "db_table": "variant2property",
                "unique_together": {("property", "variant")},
            },
        ),
        migrations.CreateModel(
            name="Variant2Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.alignment",
                    ),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.annotationtype",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.variant",
                    ),
                ),
            ],
            options={
                "db_table": "variant2annotation",
                "unique_together": {("variant", "alignment", "annotation")},
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("codon", models.TextField(blank=True, null=True)),
                ("aa", models.TextField(blank=True, null=True)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.translationgroup",
                    ),
                ),
            ],
            options={
                "db_table": "translation",
                "unique_together": {("group", "codon")},
            },
        ),
        migrations.CreateModel(
            name="Sample2Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_integer", models.BigIntegerField(blank=True, null=True)),
                (
                    "value_float",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_varchar", models.TextField(blank=True, null=True)),
                ("value_blob", models.BinaryField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_zip", models.TextField(blank=True, null=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.property",
                    ),
                ),
                (
                    "sample",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.sample",
                    ),
                ),
            ],
            options={
                "db_table": "sample2property",
                "unique_together": {("property", "sample")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="alignment2variant",
            unique_together={("variant", "alignment")},
        ),
    ]
