# Generated by Django 4.2.4 on 2023-08-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample2property",
            name="value_varchar",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variant2property",
            name="value_varchar",
            field=models.CharField(blank=True, null=True),
        ),
    ]
