# Generated by Django 4.2.4 on 2023-08-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_alter_sample2property_value_varchar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="element",
            name="accession",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="symbol",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="element",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lineages",
            name="sublineage",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="accession",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="symbol",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="datatype",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="querytype",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="standard",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="target",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="accession",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="description",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reference",
            name="organism",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="datahash",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample",
            name="name",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="sample2property",
            name="value_text",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sample2property",
            name="value_zip",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="aa",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="translation",
            name="codon",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="alt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="label",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variant",
            name="ref",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="variant2property",
            name="value_zip",
            field=models.CharField(blank=True, null=True),
        ),
    ]
