# Generated by Django 4.2.4 on 2023-08-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0003_sample_properties_alter_element_accession_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sample",
            name="properties",
            field=models.ManyToManyField(
                through="rest_api.Sample2Property", to="rest_api.property"
            ),
        ),
        migrations.AlterField(
            model_name="sample2property",
            name="value_text",
            field=models.TextField(blank=True, null=True),
        ),
    ]
