# Generated by Django 4.2.4 on 2023-08-31 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0004_sample_properties_alter_sample2property_value_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alignment",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="element",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="molecule",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reference",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="sample",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="variant",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
