# Generated by Django 4.2.4 on 2023-09-19 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0005_alter_alignment_id_alter_element_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alignment2Mutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "alignment2mutation",
            },
        ),
        migrations.CreateModel(
            name="Mutation",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("ref", models.CharField(blank=True, null=True)),
                ("alt", models.CharField(blank=True, null=True)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("parent_id", models.BigIntegerField(blank=True, null=True)),
                ("label", models.CharField(blank=True, null=True)),
                ("frameshift", models.BigIntegerField(blank=True, null=True)),
                ("sample_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "nuc_profile",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                (
                    "aa_profile",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("imported", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "collection_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "release_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("isolate", models.CharField(blank=True, max_length=50, null=True)),
                ("length", models.IntegerField(blank=True, null=True)),
                ("seq_tech", models.CharField(blank=True, max_length=50, null=True)),
                ("country", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "geo_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("host", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "genome_completeness",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "reference_accession",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "mutation",
            },
        ),
        migrations.CreateModel(
            name="Mutation2Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "db_table": "mutation2annotation",
            },
        ),
        migrations.CreateModel(
            name="Mutation2Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_integer", models.BigIntegerField(blank=True, null=True)),
                (
                    "value_float",
                    models.DecimalField(
                        blank=True, decimal_places=10, max_digits=10, null=True
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_varchar", models.CharField(blank=True, null=True)),
                ("value_blob", models.BinaryField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                ("value_zip", models.CharField(blank=True, null=True)),
                (
                    "mutation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.mutation",
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.property",
                    ),
                ),
            ],
            options={
                "db_table": "mutation2property",
                "unique_together": {("property", "mutation")},
            },
        ),
        migrations.RemoveField(
            model_name="variant",
            name="alignments",
        ),
        migrations.RemoveField(
            model_name="variant",
            name="element",
        ),
        migrations.AlterUniqueTogether(
            name="variant2annotation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="variant2annotation",
            name="alignment",
        ),
        migrations.RemoveField(
            model_name="variant2annotation",
            name="annotation",
        ),
        migrations.RemoveField(
            model_name="variant2annotation",
            name="variant",
        ),
        migrations.AlterUniqueTogether(
            name="variant2property",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="variant2property",
            name="property",
        ),
        migrations.RemoveField(
            model_name="variant2property",
            name="variant",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="properties",
        ),
        migrations.AlterField(
            model_name="alignment",
            name="sequence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="alignments",
                to="rest_api.sequence",
            ),
        ),
        migrations.AlterField(
            model_name="sample2property",
            name="sample",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="properties",
                to="rest_api.sample",
            ),
        ),
        migrations.AlterField(
            model_name="sample2property",
            name="value_float",
            field=models.DecimalField(
                blank=True, decimal_places=10, max_digits=10, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Alignment2Variant",
        ),
        migrations.DeleteModel(
            name="Variant",
        ),
        migrations.DeleteModel(
            name="Variant2Annotation",
        ),
        migrations.DeleteModel(
            name="Variant2Property",
        ),
        migrations.AddField(
            model_name="mutation2annotation",
            name="alignment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.alignment",
            ),
        ),
        migrations.AddField(
            model_name="mutation2annotation",
            name="annotation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.annotationtype",
            ),
        ),
        migrations.AddField(
            model_name="mutation2annotation",
            name="mutation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.mutation",
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="alignments",
            field=models.ManyToManyField(
                related_name="mutations",
                through="rest_api.Alignment2Mutation",
                to="rest_api.alignment",
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.element",
            ),
        ),
        migrations.AddField(
            model_name="alignment2mutation",
            name="alignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="rest_api.alignment"
            ),
        ),
        migrations.AddField(
            model_name="alignment2mutation",
            name="mutation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.mutation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mutation2annotation",
            unique_together={("mutation", "alignment", "annotation")},
        ),
        migrations.AlterUniqueTogether(
            name="alignment2mutation",
            unique_together={("mutation", "alignment")},
        ),
    ]
