# Generated by Django 4.2.4 on 2023-09-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0007_entereddata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entereddata",
            name="name",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
