# Generated by Django 4.2.4 on 2023-09-19 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0009_remove_mutation_aa_profile_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mutation",
            unique_together={
                (
                    "id",
                    "element",
                    "ref",
                    "alt",
                    "start",
                    "end",
                    "parent_id",
                    "label",
                    "frameshift",
                )
            },
        ),
    ]
