# Generated by Django 4.2.4 on 2023-09-19 10:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0011_alter_mutation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="mutation",
            unique_together=set(),
        ),
    ]
