# Generated by Django 4.2.4 on 2023-09-19 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0012_alter_mutation_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="entereddata",
            unique_together={("type", "name")},
        ),
        migrations.AlterModelTable(
            name="entereddata",
            table="entered_data",
        ),
    ]
