# Generated by Django 4.2.4 on 2023-10-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0014_sample_collection_date_sample_country_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Gene",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("symbol", models.CharField(blank=True, null=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("start", models.BigIntegerField(blank=True, null=True)),
                ("end", models.BigIntegerField(blank=True, null=True)),
                ("strand", models.BigIntegerField(blank=True, null=True)),
                ("gene_symbol", models.CharField(blank=True, null=True)),
                ("cds_symbol", models.CharField(blank=True, null=True)),
                (
                    "gene_accession",
                    models.CharField(blank=True, null=True, unique=True),
                ),
                ("cds_accession", models.CharField(blank=True, null=True, unique=True)),
                ("gene_sequence", models.TextField(blank=True, null=True)),
                ("cds_sequence", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "child_element",
            },
        ),
        migrations.CreateModel(
            name="GenePart",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("start", models.BigIntegerField()),
                ("end", models.BigIntegerField()),
                ("strand", models.BigIntegerField()),
                ("base", models.FloatField()),
                ("segment", models.BigIntegerField()),
                (
                    "gene",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.gene",
                    ),
                ),
            ],
            options={
                "db_table": "gene_part",
            },
        ),
        migrations.CreateModel(
            name="SourceElement",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("length", models.BigIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True, null=True)),
                ("standard", models.BooleanField(blank=True, null=True)),
                (
                    "molecule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="rest_api.molecule",
                    ),
                ),
            ],
            options={
                "db_table": "source_element",
            },
        ),
        migrations.RemoveField(
            model_name="element",
            name="molecule",
        ),
        migrations.RemoveField(
            model_name="sample",
            name="technology",
        ),
        migrations.DeleteModel(
            name="Elempart",
        ),
        migrations.AddField(
            model_name="gene",
            name="source_element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.sourceelement",
            ),
        ),
        migrations.AlterField(
            model_name="mutation",
            name="element",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.sourceelement",
            ),
        ),
        migrations.DeleteModel(
            name="Element",
        ),
    ]
