# Generated by Django 4.2.4 on 2023-10-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0017_remove_gene_symbol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mutation",
            name="element",
            field=models.CharField(blank=True, null=True),
        ),
    ]
