# Generated by Django 4.2.4 on 2023-10-09 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0018_alter_mutation_element"),
    ]

    operations = [
        migrations.CreateModel(
            name="Replicon",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("length", models.BigIntegerField(blank=True, null=True)),
                ("sequence", models.TextField(blank=True, null=True)),
                ("accession", models.CharField(blank=True, null=True, unique=True)),
                ("description", models.CharField(blank=True, null=True)),
                ("type", models.CharField(blank=True, null=True)),
                ("segment_number", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "replicon",
            },
        ),
        migrations.RenameModel(
            old_name="GenePart",
            new_name="GeneSegment",
        ),
        migrations.RemoveField(
            model_name="sourceelement",
            name="molecule",
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="translation",
            name="group",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="cds_accession",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="cds_symbol",
        ),
        migrations.RemoveField(
            model_name="gene",
            name="source_element",
        ),
        migrations.RemoveField(
            model_name="lineages",
            name="sublineage",
        ),
        migrations.RemoveField(
            model_name="reference",
            name="translation_group",
        ),
        migrations.AddField(
            model_name="lineages",
            name="parent_lineage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.lineages",
            ),
        ),
        migrations.AddField(
            model_name="reference",
            name="collection_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="country",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="db_xref",
            field=models.CharField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="host",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="isolate",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reference",
            name="mol_type",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lineages",
            name="lineage",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name="genesegment",
            table="gene_segment",
        ),
        migrations.DeleteModel(
            name="Molecule",
        ),
        migrations.DeleteModel(
            name="SourceElement",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.DeleteModel(
            name="TranslationGroup",
        ),
        migrations.AddField(
            model_name="replicon",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.reference",
            ),
        ),
        migrations.AddField(
            model_name="gene",
            name="replicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.replicon",
            ),
        ),
    ]
