# Generated by Django 4.2.4 on 2023-10-09 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0019_replicon_rename_genepart_genesegment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reference",
            name="standard",
        ),
    ]
