# Generated by Django 4.2.4 on 2023-10-13 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0020_remove_reference_standard"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alignment",
            name="element",
        ),
        migrations.RemoveField(
            model_name="mutation",
            name="element",
        ),
        migrations.AddField(
            model_name="alignment",
            name="gene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.gene",
            ),
        ),
        migrations.AddField(
            model_name="mutation",
            name="gene",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.gene",
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="datatype",
            field=models.CharField(default="None"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="property",
            name="name",
            field=models.CharField(default="None", unique=True),
            preserve_default=False,
        ),
    ]
