# Generated by Django 4.2.4 on 2023-10-13 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0021_remove_alignment_element_remove_mutation_element_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mutation",
            name="type",
            field=models.CharField(blank=True, null=True),
        ),
    ]
