# Generated by Django 4.2.4 on 2023-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0022_mutation_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["gene"], name="mutation_gene_id_2f1f1c_idx"),
        ),
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["start"], name="mutation_start_d58834_idx"),
        ),
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["end"], name="mutation_end_c996da_idx"),
        ),
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["ref"], name="mutation_ref_460df8_idx"),
        ),
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["alt"], name="mutation_alt_c8d6b3_idx"),
        ),
    ]
