# Generated by Django 4.2.4 on 2023-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0023_mutation_mutation_gene_id_2f1f1c_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["label"], name="mutation_label_94967f_idx"),
        ),
    ]
