# Generated by Django 4.2.4 on 2023-10-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0024_mutation_mutation_label_94967f_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alignment",
            index=models.Index(
                fields=["gene", "sequence"], name="alignment_gene_id_81f250_idx"
            ),
        ),
    ]
