# Generated by Django 4.2.4 on 2023-10-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0025_alignment_alignment_gene_id_81f250_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="alignment2mutation",
            index=models.Index(
                fields=["alignment", "mutation"], name="alignment2m_alignme_d1c719_idx"
            ),
        ),
    ]
