# Generated by Django 4.2.4 on 2023-10-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0026_alignment2mutation_alignment2m_alignme_d1c719_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="mutation",
            index=models.Index(fields=["type"], name="mutation_type_bf4ac1_idx"),
        ),
    ]
