# Generated by Django 4.2.4 on 2023-11-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0028_remove_mutation_mutation_label_94967f_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="alignment",
            name="alignment_gene_id_81f250_idx",
        ),
        migrations.RemoveField(
            model_name="alignment",
            name="gene",
        ),
        migrations.AddField(
            model_name="alignment",
            name="replicon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="rest_api.replicon",
            ),
        ),
        migrations.AddIndex(
            model_name="alignment",
            index=models.Index(
                fields=["replicon", "sequence"], name="alignment_replico_f9eb6b_idx"
            ),
        ),
    ]
