# Generated by Django 4.2.4 on 2023-11-03 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0029_remove_alignment_alignment_gene_id_81f250_idx_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Mutation2Property",
        ),
    ]
