# Generated by Django 4.2.4 on 2023-11-03 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0030_delete_mutation2property"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationtype",
            name="test",
        ),
    ]
