# Generated by Django 4.2.4 on 2023-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0031_remove_annotationtype_test"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationtype",
            name="impact",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
