# Generated by Django 4.2.4 on 2023-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0033_alter_alignment_id_alter_annotationtype_id_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mutation",
            constraint=models.UniqueConstraint(
                fields=("ref", "alt", "start", "end", "type", "gene", "replicon"),
                name="unique_mutation",
            ),
        ),
    ]
