# Generated by Django 4.2.4 on 2023-11-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0034_mutation_unique_mutation"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="mutation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("gene__isnull", True)),
                fields=("ref", "alt", "start", "end", "type", "replicon"),
                name="unique_mutation_null_gene",
            ),
        ),
    ]
